### ISSUE TITLE
Issues with `chicken-install`

### ISSUE THREAD

**Issue by nwoeanhinnogaehr** [bintracker/bintracker#1]
When I tried running `chicken install` as per the build instructions, I ran into a few issues. I'm using chicken scheme 5.2.0 on arch linux. Here's how I got around the problems:

The packages `extras` and `scm2wiki` couldn't be found. I removed both from the list and manually installed `scm2wiki` from its repo.

Compiling bintracker also required that I add the packages `byte-blob`, `base64`, `imlib2`, `web-colors`.

In the end I couldn't get the docs to build (didn't try very hard though, maybe I will later), so I just removed doc related stuff from the makefile and then the executable generated fine and works :)

p.s. Thanks for all the amazing work on this project!! It's a really fantastic idea.

**Comment by utz82** [comment]
Thanks for your report, much appreciated!
I've corrected the build instructions. Totally forgot about scm2wiki. The plan is to get it accepted into the official Chicken repo at some point but currently it's still too buggy.

For the docs, you are probably missing some Python packages (which I should add to the instructions of course). You could try `pip install --user Pygments` for a start. Anyway, please let me know if you manage to work it out.

**Comment by farvardin** [comment]
same for me. I've installed chicken 5.2.0 from source, because the one on linux-mint 19 was too old (4).

I've removed the doc because it was complicated to build. 

I got a bintracker binary, but I can't run it, the window start and just crash after that:

> Error: bad argument type - not a structure of the required type
> #f
> bt-types#app-keys
> 
> 	Call history:
> 
> 	../bintracker-core.scm:33: g300	  
> 	../bintracker-core.scm:36: pstk#tk-end	  
> 	../bintracker-core.scm:37: simple-exceptions#raise	  
> 	../bintracker.scm:42: k294	  
> 	../bintracker.scm:42: g297	  
> 	../bintracker.scm:44: bt-gui#current	  
> 	../bt-gui.scm:4087: current	  
> 	../bt-gui.scm:4079: bt-state#ui	  
> 	../bt-state.scm:32: state	  
> 	../bt-state.scm:25: chicken.string#->string	  
> 	../bt-state.scm:25: scheme#string-append	  
> 	../bt-state.scm:25: scheme#string->symbol	  
> 	../bt-state.scm:25: scheme#eval	  
> 	../bt-state.scm:24: g277	  
> 	../bintracker.scm:45: pstk#tk-end	  
> 	../bintracker.scm:46: simple-exceptions#raise	 
> 
>

**Comment by utz82** [comment]
Ugh, that doesn't look good. This might be down to changes introduced in 5.2. I'll investigate asap. For now, if you don't want to wait till I have fixed this then you could try building on 5.0 or 5.1 instead.

**Comment by utz82** [comment]
Ok, found the bug. Nothing to do with 5.2 (it does break scm2wiki though, so I'll need to look into that).

For now, uncommenting line 20 in `config/config.scm` should do the trick. I'll provide a proper fix soon. I'll also make building the docs optional.

**Comment by farvardin** [comment]
I've made it run.

I've got a few more issues:

- the doc https://bintracker.org/documentation/setup.html talks about config/emulators.scm in the case the mame binary is not called mame64. We'll have to fix this in config/systems.scm 
What operating system are you using that calls mame, "mame64"? Debian? On Ubuntu/Mint, it's simply called "mame". In the case "mame" is more widespread, maybe you could change this in the settings, and create a symbolic link on your system, it would confuse users less...

- in the doc " Copy ROM files to roms/MACHINE, where MACHINE is MAME's target system identifier string". => it's not enough to copy rom files, zx roms are often called 48.rom but bintracker requires it to be called spectrum.rom. Which is fine, maybe you could change the doc: " Copy ROM files to roms/MACHINE/MACHINE.rom, where MACHINE is MAME's target system identifier string"

but now I wonder, it's still not working this way. I've renamed the 48.rom to spectrum.rom, in roms/spectrum folder.

> focus add (block-view842 #<procedure (a37027)> #<procedure (a37033)> #<coops instance of `<ui-block-view>'>)
> focus add (order-view843 #<procedure (a37027)> #<procedure (a37033)> #<coops instance of `<ui-order-view>'>)
> spectrum.rom NOT FOUND (tried in spectrum spectrum)

The same for channelf:
> sl90025.rom NOT FOUND (tried in channelf channelf)
> sl31254.rom NOT FOUND (tried in channelf channelf)

Also, when it's crashing for this purpose, you can't exit bintracker, I had to use xkill

![image](https://user-images.githubusercontent.com/477243/85204795-2f746b80-b317-11ea-9fe4-4d547ec67a06.png)

**Comment by farvardin** [comment]
ok, I made it work. Probably our versions of Mame are quite different (mine is 0.215)

in systems.scm, I had to specify the rompath option, like this:

>  ("spectrum48" emulator: "mame" startup-args: ("spectrum" "-rompath" "roms")))

otherwise mame won't understand it had to look in the roms subfolder.

**Comment by utz82** [comment]
Done fixing the startup bug.

Regarding the application name of MAME, I'll need to find a more robust way to handle this. There should be some code that attempts to auto-detect it.

Regarding ROM names, it's pure coincidence that the Spectrum 48K ROM must be named "spectrum.rom". For the vast majority of systems, the names are pretty arbitrary. So the statement *" Copy ROM files to roms/MACHINE/MACHINE.rom, where MACHINE is MAME's target system identifier string"* would not hold true in many cases. Unfortunately MAME does not document this at all. There is a [third party site](http://adb.arcadeitalia.net) that can help with this, perhaps I should link that in the docu.

You are absolutely correct that "-rompath roms" must be passed in. That should actually be in `config/emulators.scm`. Must've accidentally dropped that line at some point. I wonder why it works for me at all.

Regarding the program not shutting down on error, yes, unfortunately there are still various places where that can happen. I can probably fix this particular instance, but ultimately this problem is caused by pstk, which needlessly crashes on the Tk side when the pipe to the calling program is lost. Haven't been able to find a good solution yet but I'm on it.

One small request for the future, it's easier for me if you open a separate ticket for each issue.

Anyway, many thanks for all your reports, and sorry you had to go through all that trouble!

**Comment by farvardin** [comment]
>  I wonder why it works for me at all.

maybe you have this setting in one config file in ~/.mame folder?

> One small request for the future, it's easier for me if you open a separate ticket for each issue.

sure, I'll do it. I've used the first issue for general starting up... I'll open a few more tickets soon

**Comment by utz82** [comment]
I've made some changes to pstk, so a crash on the Scheme side should no longer freeze Bintracker. The changes should become available through chicken-install soon. You'll need to re-install pstk and then do a full rebuild of Bintracker with `make clean && make`.

**Comment by farvardin** [comment]
I've installed again pstk and recompiled bintracker, but i didn't notice much difference so far.

**Comment by utz82** [comment]
You mean the Tk window still hangs on errors like missing ROMs? Then I'm pretty sure pstk was re-installed from your local cache. Try `chicken-uninstall pstk` followed by `chicken-install pstk`. Sorry for not being more clear about that.
