### ISSUE TITLE
Setup doc  is missing eggs

### ISSUE THREAD

**Issue by paines** [bintracker/bintracker#10]
The setup.html page is listing the eggs which are needed to compile bintracker , e.g.:
`
$ chicken-install args base64 comparse coops git imlib2 list-utils matchable pstk simple-md5 sqlite3 srfi-1 srfi-4 srfi-13 srfi-14 srfi-18 srfi-69 stack test typed-records web-colors
` 
but 2 eggs, bitstring and simple-exceptions  are missing in order to exectue "make" in the build directory successfully.

**Comment by utz82** [comment]
Thank you very much for the report. I've added the bitstring egg 
dependency to the build instructions, and removed a leftover import of 
simple-exceptions which was still hiding in the code.

**Comment by utz82** [comment]
Thank you for the report! I've added the bitstring dependency to the build instructions, and removed a spurious reference to simple-exceptions, which was still hiding in the code.

**Comment by paines** [comment]
Glad I could help. Keep up the great work. We need more chicken software / solutions.
