### ISSUE TITLE
problem when buildin

### ISSUE THREAD

**Issue by DeMOSic** [bintracker/bintracker#11]
btw, i renamed Makefile.mingw to Makefile beforehand. this is weird

![image](https://user-images.githubusercontent.com/82211203/165097135-8ddc51ce-170c-4210-972e-24251b4fe848.png)

**Comment by utz82** [comment]
Thanks for the report. Unfortunately mingw builds are broken. I'm currently working on an alternative but I need some more time.

**Comment by utz82** [comment]
Fixed.
