### ISSUE TITLE
Tk file picker crash

### ISSUE THREAD

**Issue by LoKiToon** [bintracker/bintracker#13]
https://user-images.githubusercontent.com/98922449/219368759-fce7c487-ea44-40ea-8177-974895ee4790.mp4

**Comment by utz82** [comment]
Thanks for the report, confirmed. Bummer, I thought I had recently fixed this. Apparently not.

**Comment by utz82** [comment]
Hopefully this will do the trick. Please test if you have the time.

**Comment by LoKiToon** [comment]
Okay, I will test it now

**Comment by LoKiToon** [comment]
I've recreated what I did, and as I tried to play the tune, it crashed. 
![image](https://user-images.githubusercontent.com/98922449/219570992-94e421ff-082d-46d3-af7e-1b34effd3db2.png)

**Comment by utz82** [comment]
Thanks. Wow, this is getting stranger and stranger. I'll have to investigate a bit more in depth.

**Comment by utz82** [comment]
Alright, I'll need your exact tcl/tk version. In a terminal, run `tclsh`. Then, in tclsh
```
puts [info patchlevel]
```
Ctrl-D or `exit` quits tclsh.

**Comment by LoKiToon** [comment]
![image](https://user-images.githubusercontent.com/98922449/219619324-c241cabd-cb37-466c-9456-e4e33c734a38.png)

**Comment by utz82** [comment]
Thanks. And if you check in your package manager, it probably says 8.6.13, right? The package in question is most likely called "tcl".

**Comment by LoKiToon** [comment]
Just "tcl"? Version number for that is 8.6.11
![image](https://user-images.githubusercontent.com/98922449/219623639-aa222587-8fa2-4060-a2b7-d555ca47489d.png)

**Comment by utz82** [comment]
Wow, just wow. Ok, thanks for now, I'm on it.

**Comment by utz82** [comment]
Found and fixed the problem causing the latest crash. Guess I should've paid more attention with my previous attempt at fixing the original bug. I'm hoping I also got rid of the latter this time. Please test if it works for you now.

**Comment by LoKiToon** [comment]
Okay, I will test now.

**Comment by LoKiToon** [comment]
It's fixed :+1:

**Comment by utz82** [comment]
Yay! Again, thank you so much for your support.

**Comment by LoKiToon** [comment]
No problem
