### ISSUE TITLE
Crash when editing Step value

### ISSUE THREAD

**Issue by LoKiToon** [bintracker/bintracker#14]
Also crashes when putting letters on the values
https://user-images.githubusercontent.com/98922449/219468680-497d1afd-d711-489f-88f1-83422b45afcd.mp4

**Comment by utz82** [comment]
Thanks for the report, much appreciated. This one is a bit odd. I can reproduce the crash for putting a letter as value, but not for for step = 0. I'll see if I can find a fix for this, will probably need your help in testing it though. In the meantime, could you tell me what version of Tcl/Tk you are running?

**Comment by LoKiToon** [comment]
I believe the Tk version I use is 8.6. Let me make it a bit more clear, on the video, I clicked the arrow twice, which made the value negative. (-1)

**Comment by utz82** [comment]
Ah, missed that. Thanks for the clarification, now I can reproduce everything.

**Comment by utz82** [comment]
Done. Ideally we'd be able to use hexadecimal numbers for step values, but that's a whole different can of worms. Thanks again for your help!

**Comment by LoKiToon** [comment]
No problem.
