### ISSUE TITLE
mame starts and capture the mouse

### ISSUE THREAD

**Issue by farvardin** [bintracker/bintracker#4]
if mame could start without capturing the mouse, it would provide a better bintracker experience. 

At the moment, after opening a song, when mame starts, it captures the mouse (the pointer will disappear) and I have to use "alt" + "tab" to get my mouse again.

I've looked at the man pages, and this option doesn't seems to be possible.

**Comment by utz82** [comment]
Not cool, mouse capturing should normally be disabled in MAME by default. I can't reproduce it on 0.209, so something must've changed in the meantime. Does adding `-nomouse` to the options in `emulators.scm` help?

**Comment by farvardin** [comment]
when I've read the man page, I thought this option wasn't relevant because it said the "default is OFF (nomouse)" (and I also though it was for disabling mouse in emulated system). But maybe it was changed afterwards. Adding this option prevents capturing the mouse, so you could add this in emulators.scm!

**Comment by utz82** [comment]
Good idea, I've added it.
I don't think that this is intentional, actually. Care to file a bug against https://github.com/mamedev/mame ? I'll do it myself if you can't be bothered.

**Comment by farvardin** [comment]
done: https://github.com/mamedev/mame/issues/6847

**Comment by utz82** [comment]
Closing this, since not much else can be done regarding this from Bintracker's side.
