### ISSUE TITLE
can't open a new module after closing one

### ISSUE THREAD

**Issue by farvardin** [bintracker/bintracker#5]
- after we load or open a song, if we request to open a new one with the icon (or control+o), it will close the previous one and we start at the intro screen. But we can't open a new song, the buttons don't react to click input. We can't close bintracker either (we must use xkill to kill the window)

- if we open a song using the menu, bintracker will crash:

Warning (#<thread: thread472>): in thread: (-) bad argument type - not a number: #f

	Call history:

	../bt-state.scm:112: scheme#eval	  
	../bt-state.scm:113: bt-types#settings	  
	../bt-types.scm:150: chicken.base#alist-ref	  
	../bt-state.scm:111: g393	  
	../bt-state.scm:149: list-utils#alist-inverse-ref	  
	../bt-state.scm:158: chicken.string#->string	  
	../bt-state.scm:158: chicken.string#string-translate	  
	../bt-state.scm:158: srfi-13#string-upcase	  
	../bt-gui.scm:913: scheme#string-append	  
	../bt-gui.scm:910: ui-modeline-set	  
	../bt-gui.scm:732: coops#slot-value	  
	../bt-gui.scm:732: chicken.base#alist-ref	  
	../bt-gui.scm:733: scheme#string-append	  
	../bt-gui.scm:733: label	  
	../bt-gui.scm:1847: chicken.string#string-split	  
	../bt-gui.scm:1846: g6616	  	<--

Error: uncaught exception: #<condition: (exn type)>

	Call history:

	../bt-state.scm:25: scheme#string-append	  
	../bt-state.scm:25: scheme#string->symbol	  
	../bt-state.scm:25: scheme#eval	  
	../bt-state.scm:24: g277	  
	../bt-gui.scm:4079: ui-ref	  
	../bt-gui.scm:686: ui-children	  
	../bt-gui.scm:642: coops#slot-value	  
	../bt-gui.scm:687: ui-children	  
	../bt-gui.scm:642: coops#slot-value	  
	../bt-gui.scm:688: chicken.base#alist-ref	  
	../bt-gui.scm:4088: ui-metastate	  
	../bt-gui.scm:4039: coops#slot-value	  
	../bt-gui.scm:3763: coops#slot-value	  
	../bintracker.scm:44: g301	  
	../bintracker.scm:45: pstk#tk-end	  
	../bintracker.scm:46: simple-exceptions#raise	  	<--

**Comment by utz82** [comment]
Thanks for the report. This might be a bit more difficult to fix.
As a work-around, clicking somewhere on an empty spot in the application window sometimes fixes things when BT doesn't react to input.

**Comment by farvardin** [comment]
do you get the same behavior when open files? 

I couldn't get it to work again by clicking this way. I don't have any error message in the terminal.

**Comment by utz82** [comment]
No, works fine for me. But I have seen this kind of bug before so I have some ideas where to look. I might ask you to try some things later on (probably in a few days), if that's ok with you.

**Comment by farvardin** [comment]
sure

**Comment by utz82** [comment]
^^ This might solve the issue, not sure.
